apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppeteer-gke
  namespace: puppeteer-gke-ns
  labels:
    app: puppeteer-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppeteer-gke
  template:
    metadata:
      labels:
        app: puppeteer-gke
    spec:
      containers:
        - name: screenshotter
          image: "path to your artifactory docker image"
          resources:
            requests:
              cpu: 2000m
              memory: 1024Mi
